image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup & Prepare
    init: |
      # Dieses Skript wird in der Regel nur einmal ausgeführt, um die Struktur zu initialisieren.
      # ./setup_gitpod_project.sh # Nicht rekursiv aufrufen!
      echo "Gitpod Umgebung wird basierend auf Dockerfile und requirements.txt vorbereitet."
    command: |
      echo "Workspace ist bereit. Führen Sie Ihr Training aus mit: python train_model.py"
      # Halten Sie das Terminal offen, damit der Container nicht sofort beendet wird.
      tail -f /dev/null
